### ISSUE TITLE
Add option to record events to file

### ISSUE THREAD

**Issue by pgleeson** [LEMS/jLEMS#67]
A very useful addition to LEMS would be the ability to record (spiking) events in a simulation to file.

Suggested by @FinnK, but also of interest to @borismarin, @robertcannon 

A suggestion for implementation: could possibly be enabled by the addition of a new element in `<Simulation>`, similar to `<OutputFile>`:

    <EventOutputFile id="spikes" fileName="results/iaf_v.dat" select="iafTauPop[*]" eventPort="spike"/>

The saved data in the file would be the the time of the event followed by index of the cell, e.g.

0.01  3
0.03  4
0.05  3
0.07  2
0.07  1

**Comment by borismarin** [comment]
+1
Maybe the "event" attribute should be named "eventPort" instead.

**Comment by FinnK** [comment]
all other variables like statevariables and derivedvariables are included in an <OutputFile>, is there anything to be said for including eventports in the same output file and the same display as the variables? the result for something like that would simply be 0s for no spike and 1 for a spike as below:

0.01 0
0.02 0
0.03 0 
0.04 0
0.05 1
0.06 0

This would be useful for example to see spikes in the same diagram as all the traces to determine that a model functions as expected. 

However, additionally something like <EventOutputFile> would be interesting for recording just spikes, and could be aligned to other standards? like address event representation https://web.stanford.edu/group/brainsinsilicon/documents/methAER.pdf or perhaps a text format that can easily be turned into a raster plot, with population name, neuron id, and then timestamps:

popA[1] 0.07
popA[2] 0.07
popA[3] 0.01 0.05
popA[4] 0.03

**Comment by pgleeson** [comment]
It might be best to concentrate all this behaviour in one class so maybe have an attribute on EventOutputFile to specify the output format? e.g.

     <EventOutputFile id=... format="minimal"/>

0.01 3
0.03 4
0.05 3
0.07 2
0.07 1

     <EventOutputFile id=... format="alltimes"/>

0.00   0 0 0 
0.01   0 0 1
0.02   0 0 0 
0.03   1 0 0 

     <EventOutputFile id=... format="aer"/>

popA[1] 0.07
popA[2] 0.07
popA[3] 0.01 0.05
popA[4] 0.03

**Comment by FinnK** [comment]
That sounds great! I think better naming for the last scenario would be raster, aer would need source and destination fields.

Would it be useful to have any functionality in the <display> element related to spikes? Or should that be completely separate?

**Comment by pgleeson** [comment]
@FinnK I'm planning to look into adding some basic spike recording mechanism like this in the next few days. Just checking in case you had done something about this too.

**Comment by pgleeson** [comment]
@FinnK this is now in the development branches. See https://github.com/NeuroML/NeuroML2/blob/development/LEMSexamples/LEMS_NML2_Ex23_Spiketimes.xml for an example.

It can save spikes in 2 of the ways mentioned above (id time) or (time id) and could be extended by adding more formats here: https://github.com/LEMS/jLEMS/blob/c0fc4bc608f72910bd8ba887fd2fe79bd348752e/src/main/java/org/lemsml/jlems/io/out/FileEventResultWriter.java#L47
