### ISSUE TITLE
Add support for Heaviside function

### ISSUE THREAD

**Issue by pgleeson** [LEMS/jLEMS#80]

**Comment by borismarin** [comment]
@pgleeson notation: capital H?

**Comment by pgleeson** [comment]
Yes. Example of expression to be parsed: (H(p - 100) * 3.0E-7) * (1 + (p / 100))

https://github.com/OpenSourceBrain/CA1PyramidalCell/blob/master/neuroConstruct/generatedNeuroML2/CA1.cell.nml#L19840
