### ISSUE TITLE
Explicit connection between variables from different components

### ISSUE THREAD

**Issue by kosti1992** [LEMS/jLEMS#87]
Hello, 
while working on a transformation from NestML to LEMS I have faced a problem which is somehow related to lack of expressiveness in LEMS.  
Currently, the _EventConnection_ element seems to be the sole possibility to connect two components. While port to port connections work fine, it is not possible to establish a  
direct connection between two variables of different components. Therefore, I would like to know if there is a possibility to somehow connect two variables from two distinct components, 
e.g. two different neurons.  
 
Regards Konstantin

**Comment by pgleeson** [comment]
@kosti1992 It is possible to use a variable directly in another component if the source is a parent of the other, e.g. use Exposure in the one controlling the value of that variable (e.g. v), and use Requirement in the child component, which can then read the value of that as a variable in its expressions. You can't have one variable being a state variable/derived variable in 2 or more components, one has to be the main place where that value is determined, and the other just uses it. If it is a variable (e.g. temperature) which multiple neurons/ion channels need to access, put it at the highest level that's common to all using components, e.g. the network: https://github.com/NeuroML/NeuroML2/blob/master/LEMSexamples/LEMS_NML2_Ex17_Tissue.xml#L23 

Another possibility if you do need analog connections between neurons is to use an analog synapse, e.g. https://github.com/NeuroML/NeuroML2/blob/development/examples/NML2_AnalogSynapsesHH.nml. Here you can create a generic component which produces a continuously transmitting current which is a function of v, see https://github.com/NeuroML/NeuroML2/blob/development/NeuroML2CoreTypes/Synapses.xml#L484. This could be extended to be a function of some other cell variable, e.g. ca_conc, "activity", and even transmit some other variable (e.g. input rate) to the other neuron via a (weighted) continuousConnection, but the neuron should be equipped with Attachments to know what to do with the incoming variables from the connections (they generally know what to do with incoming currents).

**Comment by kosti1992** [comment]
@pgleeson thank you for the detailed explanation. The first approach is less applicable in my case, since it would lead to a situation where we have to provide for each connection between two sub-components a single variable in the super-component, in worst case  a quadratic number of variables. The second approach seems to be more promising. I will take a look at it and get back in touch if there are any problems.
